OPENAI_API_KEY = "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"
LANGCHAIN_TRACING_V2 = 'true'
LANGCHAIN_ENDPOINT = 'https://api.smith.langchain.com'
LANGCHAIN_API_KEY = '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'
LANGCHAIN_PROJECT = 'pr-indelible-whelp-78'
GOOGLE_API_KEY = "AIzaSyDK1nGKwa9eiwiQ6_VJOQ7eAQHb21Y5UyU"